name: Cập nhật Bảng xếp hạng

on:
  schedule:
    - cron: "11 */1 * * *"
  workflow_dispatch:

env:
  TOKEN: ${{ secrets.TOKEN }}

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.TOKEN }}
      - name: Thiết lập Python '3.12'
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'
      - name: Cài đặt dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Cập nhật Bảng xếp hạng
        run: python bot_leaderboard.py
      - name: Cam kết & Đẩy tệp
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add -A
          git commit -m "Cập nhật bảng xếp hạng"
          git push --force